theme: jekyll-theme-time-machine
tite: Welcome to LRP Glosses!
description: You'll find here passages related to law in Christianity. Every page is glossed using the plug-in Hypothesis. Go to my pages, sign in to Hypothesis, and add to the analysis of the texts.
